// <auto-generated />
namespace Eventify.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingNotificationStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNotificationStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201508324_AddingNotificationStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
